// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillUpAcademy.Infrastructure.Datos;

#nullable disable

namespace SkillUpAcademy.Infrastructure.Datos.Migraciones
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324093759_AgregarEstaBloqueadoIA")]
    partial class AgregarEstaBloqueadoIA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("roles_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("usuarios_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("usuarios_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("usuarios_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("usuarios_tokens", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.AreaHabilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ColorAcento")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_acento");

                    b.Property<string>("ColorPrimario")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_primario");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Icono")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("icono");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<string>("Subtitulo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subtitulo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("areas_habilidad", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.ConfiguracionAvatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ColorFondo")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_fondo");

                    b.Property<string>("DescripcionPersonalidad")
                        .HasColumnType("text")
                        .HasColumnName("descripcion_personalidad");

                    b.Property<bool>("EsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_default");

                    b.Property<string>("EstiloCelebracion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("moderado")
                        .HasColumnName("estilo_celebracion");

                    b.Property<string>("EstiloCorreccion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("constructivo")
                        .HasColumnName("estilo_correccion");

                    b.Property<string>("EstiloVisual")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("corporativa")
                        .HasColumnName("estilo_visual");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("NombreAvatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Aria")
                        .HasColumnName("nombre_avatar");

                    b.Property<string>("PromptSistemaBase")
                        .HasColumnType("text")
                        .HasColumnName("prompt_sistema_base");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<string>("Tono")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("profesional")
                        .HasColumnName("tono");

                    b.Property<decimal>("VelocidadHabla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("velocidad_habla");

                    b.Property<string>("VozTTS")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("es-ES-ElviraNeural")
                        .HasColumnName("voz_tts");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("configuraciones_avatar", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.EleccionEscenarioUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EscenarioId")
                        .HasColumnType("integer")
                        .HasColumnName("escenario_id");

                    b.Property<DateTime>("FechaEleccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_eleccion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("OpcionEscenarioId")
                        .HasColumnType("integer")
                        .HasColumnName("opcion_escenario_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("EscenarioId");

                    b.HasIndex("OpcionEscenarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("elecciones_escenario_usuario", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.EscenaLeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenidoVisual")
                        .HasColumnType("text")
                        .HasColumnName("contenido_visual");

                    b.Property<int>("DuracionSegundos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15)
                        .HasColumnName("duracion_segundos");

                    b.Property<bool>("EsPausaReflexiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_pausa_reflexiva");

                    b.Property<string>("GuionAria")
                        .HasColumnType("text")
                        .HasColumnName("guion_aria");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("layout");

                    b.Property<int>("LeccionId")
                        .HasColumnType("integer")
                        .HasColumnName("leccion_id");

                    b.Property<string>("MetadatosVisuales")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadatos_visuales");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("SegundosPausa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("segundos_pausa");

                    b.Property<string>("TipoContenidoVisual")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_contenido_visual");

                    b.Property<string>("TituloEscena")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo_escena");

                    b.Property<string>("TransicionEntrada")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transicion_entrada");

                    b.HasKey("Id");

                    b.HasIndex("LeccionId", "Orden");

                    b.ToTable("escenas_leccion", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.Escenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contexto")
                        .HasColumnType("text")
                        .HasColumnName("contexto");

                    b.Property<string>("GuionAudio")
                        .HasColumnType("text")
                        .HasColumnName("guion_audio");

                    b.Property<int>("LeccionId")
                        .HasColumnType("integer")
                        .HasColumnName("leccion_id");

                    b.Property<string>("TextoSituacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto_situacion");

                    b.HasKey("Id");

                    b.HasIndex("LeccionId");

                    b.ToTable("escenarios", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.Leccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Contenido")
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<int>("DuracionMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("duracion_minutos");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("GuionAudio")
                        .HasColumnType("text")
                        .HasColumnName("guion_audio");

                    b.Property<int>("NivelId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_id");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<string>("PuntosClave")
                        .HasColumnType("jsonb")
                        .HasColumnName("puntos_clave");

                    b.Property<int>("PuntosRecompensa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("puntos_recompensa");

                    b.Property<string>("TipoLeccion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_leccion");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("NivelId");

                    b.ToTable("lecciones", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.Logro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condicion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("condicion");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Icono")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("icono");

                    b.Property<int>("PuntosRequeridos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("puntos_requeridos");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("logros", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.LogroUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaDesbloqueo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_desbloqueo")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("LogroId")
                        .HasColumnType("integer")
                        .HasColumnName("logro_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("LogroId");

                    b.HasIndex("UsuarioId", "LogroId")
                        .IsUnique();

                    b.ToTable("logros_usuario", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.MensajeChatIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_envio")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("FueMarcado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("fue_marcado");

                    b.Property<string>("MotivoMarca")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo_marca");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.Property<int>("TokensUsados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tokens_usados");

                    b.HasKey("Id");

                    b.HasIndex("SesionId");

                    b.ToTable("mensajes_chat_ia", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("AreaHabilidadId")
                        .HasColumnType("integer")
                        .HasColumnName("area_habilidad_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("NumeroNivel")
                        .HasColumnType("integer")
                        .HasColumnName("numero_nivel");

                    b.Property<int>("PuntosDesbloqueo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("puntos_desbloqueo");

                    b.HasKey("Id");

                    b.HasIndex("AreaHabilidadId", "NumeroNivel")
                        .IsUnique();

                    b.ToTable("niveles", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.OpcionEscenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EscenarioId")
                        .HasColumnType("integer")
                        .HasColumnName("escenario_id");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<int>("PuntosOtorgados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("puntos_otorgados");

                    b.Property<int?>("SiguienteEscenarioId")
                        .HasColumnType("integer")
                        .HasColumnName("siguiente_escenario_id");

                    b.Property<string>("TextoOpcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("texto_opcion");

                    b.Property<string>("TextoRetroalimentacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto_retroalimentacion");

                    b.Property<string>("TipoResultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_resultado");

                    b.HasKey("Id");

                    b.HasIndex("EscenarioId");

                    b.HasIndex("SiguienteEscenarioId");

                    b.ToTable("opciones_escenario", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.OpcionQuiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsCorrecta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_correcta");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<int>("PreguntaQuizId")
                        .HasColumnType("integer")
                        .HasColumnName("pregunta_quiz_id");

                    b.Property<string>("Retroalimentacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("retroalimentacion");

                    b.Property<string>("TextoOpcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("texto_opcion");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaQuizId");

                    b.ToTable("opciones_quiz", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.PreguntaQuiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Explicacion")
                        .HasColumnType("text")
                        .HasColumnName("explicacion");

                    b.Property<int>("LeccionId")
                        .HasColumnType("integer")
                        .HasColumnName("leccion_id");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<string>("TextoPregunta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto_pregunta");

                    b.HasKey("Id");

                    b.HasIndex("LeccionId");

                    b.ToTable("preguntas_quiz", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.ProgresoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("NoIniciado")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_completado");

                    b.Property<int>("Intentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("intentos");

                    b.Property<int>("LeccionId")
                        .HasColumnType("integer")
                        .HasColumnName("leccion_id");

                    b.Property<int>("Puntuacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("puntuacion");

                    b.Property<DateTime>("UltimoAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("ultimo_acceso")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("LeccionId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "LeccionId")
                        .IsUnique();

                    b.ToTable("progreso_usuario", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.RecursoVisual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EscenaLeccionId")
                        .HasColumnType("integer")
                        .HasColumnName("escena_leccion_id");

                    b.Property<string>("Etiquetas")
                        .HasColumnType("jsonb")
                        .HasColumnName("etiquetas");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("TextoAlternativo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("texto_alternativo");

                    b.Property<string>("TipoMime")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_mime");

                    b.Property<string>("TipoRecurso")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_recurso");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("EscenaLeccionId");

                    b.ToTable("recursos_visuales", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.RegistroAbuso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccionTomada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("accion_tomada");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("MensajeOriginal")
                        .HasColumnType("text")
                        .HasColumnName("mensaje_original");

                    b.Property<string>("MetodoDeteccion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("metodo_deteccion");

                    b.Property<Guid?>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.Property<string>("TipoViolacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_violacion");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("SesionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("registros_abuso", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.RespuestaQuizUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("boolean")
                        .HasColumnName("es_correcta");

                    b.Property<DateTime>("FechaRespuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_respuesta")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("OpcionSeleccionadaId")
                        .HasColumnType("integer")
                        .HasColumnName("opcion_seleccionada_id");

                    b.Property<int>("PreguntaQuizId")
                        .HasColumnType("integer")
                        .HasColumnName("pregunta_quiz_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("OpcionSeleccionadaId");

                    b.HasIndex("PreguntaQuizId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("respuestas_quiz_usuario", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.SesionChatIA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<int>("ContadorMensajes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("contador_mensajes");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_inicio")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("FueMarcada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("fue_marcada");

                    b.Property<int?>("LeccionId")
                        .HasColumnType("integer")
                        .HasColumnName("leccion_id");

                    b.Property<string>("TipoSesion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_sesion");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("LeccionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("sesiones_chat_ia", (string)null);
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.UsuarioApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<bool>("AudioHabilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("audio_habilitado");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaBloqueadoIA")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("IdiomaPreferido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("es")
                        .HasColumnName("idioma_preferido");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("PuntosTotales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("puntos_totales");

                    b.Property<int>("RachaDias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("racha_dias");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UltimaFechaActividad")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ultima_fecha_actividad");

                    b.Property<DateTime>("UltimoAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("ultimo_acceso")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UrlAvatar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_avatar");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.UsuarioApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.UsuarioApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillUpAcademy.Core.Entidades.UsuarioApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.UsuarioApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.EleccionEscenarioUsuario", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.Escenario", "Escenario")
                        .WithMany()
                        .HasForeignKey("EscenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillUpAcademy.Core.Entidades.OpcionEscenario", "OpcionEscenario")
                        .WithMany()
                        .HasForeignKey("OpcionEscenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillUpAcademy.Core.Entidades.UsuarioApp", "Usuario")
                        .WithMany("EleccionesEscenario")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escenario");

                    b.Navigation("OpcionEscenario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.EscenaLeccion", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.Leccion", "Leccion")
                        .WithMany("Escenas")
                        .HasForeignKey("LeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leccion");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.Escenario", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.Leccion", "Leccion")
                        .WithMany("Escenarios")
                        .HasForeignKey("LeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leccion");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.Leccion", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.Nivel", "Nivel")
                        .WithMany("Lecciones")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.LogroUsuario", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.Logro", "Logro")
                        .WithMany("LogrosUsuario")
                        .HasForeignKey("LogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillUpAcademy.Core.Entidades.UsuarioApp", "Usuario")
                        .WithMany("Logros")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.MensajeChatIA", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.SesionChatIA", "Sesion")
                        .WithMany("Mensajes")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.Nivel", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.AreaHabilidad", "AreaHabilidad")
                        .WithMany("Niveles")
                        .HasForeignKey("AreaHabilidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaHabilidad");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.OpcionEscenario", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.Escenario", "Escenario")
                        .WithMany("Opciones")
                        .HasForeignKey("EscenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillUpAcademy.Core.Entidades.Escenario", "SiguienteEscenario")
                        .WithMany()
                        .HasForeignKey("SiguienteEscenarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Escenario");

                    b.Navigation("SiguienteEscenario");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.OpcionQuiz", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.PreguntaQuiz", "PreguntaQuiz")
                        .WithMany("Opciones")
                        .HasForeignKey("PreguntaQuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreguntaQuiz");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.PreguntaQuiz", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.Leccion", "Leccion")
                        .WithMany("PreguntasQuiz")
                        .HasForeignKey("LeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leccion");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.ProgresoUsuario", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.Leccion", "Leccion")
                        .WithMany("Progresos")
                        .HasForeignKey("LeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillUpAcademy.Core.Entidades.UsuarioApp", "Usuario")
                        .WithMany("Progresos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.RecursoVisual", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.EscenaLeccion", "EscenaLeccion")
                        .WithMany("Recursos")
                        .HasForeignKey("EscenaLeccionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EscenaLeccion");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.RegistroAbuso", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.SesionChatIA", "Sesion")
                        .WithMany()
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SkillUpAcademy.Core.Entidades.UsuarioApp", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sesion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.RespuestaQuizUsuario", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.OpcionQuiz", "OpcionSeleccionada")
                        .WithMany()
                        .HasForeignKey("OpcionSeleccionadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillUpAcademy.Core.Entidades.PreguntaQuiz", "PreguntaQuiz")
                        .WithMany()
                        .HasForeignKey("PreguntaQuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillUpAcademy.Core.Entidades.UsuarioApp", "Usuario")
                        .WithMany("RespuestasQuiz")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpcionSeleccionada");

                    b.Navigation("PreguntaQuiz");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.SesionChatIA", b =>
                {
                    b.HasOne("SkillUpAcademy.Core.Entidades.Leccion", "Leccion")
                        .WithMany()
                        .HasForeignKey("LeccionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SkillUpAcademy.Core.Entidades.UsuarioApp", "Usuario")
                        .WithMany("SesionesChatIA")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.AreaHabilidad", b =>
                {
                    b.Navigation("Niveles");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.EscenaLeccion", b =>
                {
                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.Escenario", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.Leccion", b =>
                {
                    b.Navigation("Escenarios");

                    b.Navigation("Escenas");

                    b.Navigation("PreguntasQuiz");

                    b.Navigation("Progresos");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.Logro", b =>
                {
                    b.Navigation("LogrosUsuario");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.Nivel", b =>
                {
                    b.Navigation("Lecciones");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.PreguntaQuiz", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.SesionChatIA", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("SkillUpAcademy.Core.Entidades.UsuarioApp", b =>
                {
                    b.Navigation("EleccionesEscenario");

                    b.Navigation("Logros");

                    b.Navigation("Progresos");

                    b.Navigation("RespuestasQuiz");

                    b.Navigation("SesionesChatIA");
                });
#pragma warning restore 612, 618
        }
    }
}
